"""record price at purchase

Revision ID: 2eb75835b3e0
Revises: 7d3c061955d4
Create Date: 2026-08-30 22:05:48.072693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb75835b3e0'
down_revision: Union[str, Sequence[str], None] = '7d3c061955d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_products', 'price_at_purchase')
    # ### end Alembic commands ###
