"""add is_verified to clients

Revision ID: 4ce500214edf
Revises: 820fa5236f8e
Create Date: 2026-04-15 11:59:49.438565

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce500214edf'
down_revision: Union[str, Sequence[str], None] = '820fa5236f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_verified')
    # ### end Alembic commands ###
