"""add column address to table Client

Revision ID: b36dd21d1c9b
Revises: ddfab4ee855e
Create Date: 2026-04-25 20:09:17.609620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36dd21d1c9b'
down_revision: Union[str, Sequence[str], None] = 'ddfab4ee855e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address')
    # ### end Alembic commands ###
