"""unique review per client and product

Revision ID: e62abf245480
Revises: 76ece0417acd
Create Date: 2026-08-30 22:29:41.552494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e62abf245480'
down_revision: Union[str, Sequence[str], None] = '76ece0417acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # Rows written before this rule existed can already break it, and then
    # create_unique_constraint fails. Keep the first review of each pair.
    op.execute(
        """
        DELETE FROM reviews a
        USING reviews b
        WHERE a.client_id = b.client_id
          AND a.product_id = b.product_id
          AND a.id > b.id
        """
    )
    op.create_unique_constraint('uq_review_per_client_product', 'reviews', ['client_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_per_client_product', 'reviews', type_='unique')
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
